import type { IntentDefinition } from "./types";
import slotDefs from "../knowledge/slot-definitions.json";

export const INTENT_DEFINITIONS: IntentDefinition[] = [
  {
    intent: "ALQUILER_EXAMEN",
    aliases: ["alquiler", "alquilar", "vehículo para examen", "carro para examen", "auto para examen", "vehículo para mi examen"],
    requiredSlots: slotDefs.ALQUILER_EXAMEN.requiredSlots as IntentDefinition["requiredSlots"],
    optionalSlots: [],
    tools: ["consultar_categorias"],
    exitConditions: ["reserva_creada", "handoff"],
    businessRules: ["No incluye examen de reglas", "Solo vehículo para examen práctico"],
  },
  {
    intent: "SIMULACRO",
    aliases: ["simulacro", "simulación", "prueba de examen"],
    requiredSlots: slotDefs.SIMULACRO.requiredSlots as IntentDefinition["requiredSlots"],
    optionalSlots: [],
    tools: ["consultar_agenda", "consultar_disponibilidad", "consultar_fechas_disponibles", "crear_reserva"],
    exitConditions: ["reserva_creada", "handoff"],
    businessRules: ["Se realiza en el circuito donde se hace el examen práctico", "Duración 20 min"],
  },
  {
    intent: "PRACTICA",
    aliases: ["práctica", "practicar", "manejar", "conducir", "clase"],
    requiredSlots: slotDefs.PRACTICA.requiredSlots as IntentDefinition["requiredSlots"],
    optionalSlots: [],
    tools: ["consultar_agenda", "consultar_disponibilidad", "consultar_fechas_disponibles", "crear_reserva"],
    exitConditions: ["reserva_creada", "handoff"],
    businessRules: ["Con instructor", "Circuito alterno es copia idéntica del oficial", "Duración 30 min"],
  },
  {
    intent: "PAQUETE",
    aliases: ["paquete", "paquetes", "todo incluido", "promoción", "promo"],
    requiredSlots: slotDefs.PAQUETE.requiredSlots as IntentDefinition["requiredSlots"],
    optionalSlots: [],
    tools: ["consultar_paquetes"],
    exitConditions: ["info_proporcionada", "reserva_creada", "handoff"],
    businessRules: ["P1-P5 disponibles", "QR cubre total del paquete"],
  },
  {
    intent: "HORARIOS",
    aliases: ["horario", "horarios", "atención", "atienden", "abierto", "cierran"],
    requiredSlots: [],
    optionalSlots: [],
    tools: ["consultar_agenda"],
    exitConditions: ["info_proporcionada"],
    businessRules: ["Todos los días incluye domingos y feriados"],
  },
  {
    intent: "RESERVA",
    aliases: ["cita", "reservar", "reserva", "agendar", "agenda", "turno", "sacar cita"],
    requiredSlots: slotDefs.RESERVA.requiredSlots as IntentDefinition["requiredSlots"],
    optionalSlots: [],
    tools: ["consultar_agenda", "consultar_disponibilidad", "consultar_fechas_disponibles", "crear_reserva"],
    exitConditions: ["reserva_creada", "handoff"],
    businessRules: ["Pago previo obligatorio", "Se comparte QR"],
  },
  {
    intent: "PAGO",
    aliases: ["pagar", "pago", "yape", "plin", "transferencia", "comprobante", "qr"],
    requiredSlots: [],
    optionalSlots: [],
    tools: [],
    exitConditions: ["handoff"],
    businessRules: ["Se comparte QR", "Se paga por Yape o Plin", "Se envía comprobante"],
  },
  {
    intent: "HANDOFF",
    aliases: ["asesor", "humano", "persona", "hablar con alguien", "ayuda humana"],
    requiredSlots: [],
    optionalSlots: [],
    tools: [],
    exitConditions: ["handoff"],
    businessRules: [],
  },
];
